import { p256 } from '@noble/curves/nist.js';
import { hkdf } from '@noble/hashes/hkdf.js';
import { hmac } from '@noble/hashes/hmac.js';
import { sha256 } from '@noble/hashes/sha2.js';
import { randomBytes } from 'node:crypto';
import { bigIntToBytes, bytesToBigInt, concat, equalBytes, u64le, utf8 } from './bytes.js';

/**
 * SPAKE2 as specified by RFC 9382, ciphersuite SPAKE2-P256-SHA256-HKDF-HMAC.
 *
 * This is the only suite the RFC publishes test vectors for, which is why it
 * was chosen: every step below is checked against Appendix B. The curve
 * arithmetic, hash, HKDF and HMAC all come from the audited @noble libraries;
 * this file only wires them together in the order the RFC prescribes.
 *
 * Role A sends pA = w·M + x·P, role B sends pB = w·N + y·P. Both derive
 * K = x·y·P, build the transcript TT, and split Hash(TT) into Ke (the shared
 * secret handed to the caller) and Ka (from which confirmation keys come).
 * Neither side may use Ke until it has verified the peer's confirmation MAC.
 */

const Point = p256.Point;
const ORDER = Point.Fn.ORDER;

/** Fixed points from RFC 9382 section 6, generated by hashing to the curve. */
export const SPAKE2_M = Point.fromHex('02886e2f97ace46e55ba9dd7242579f2993b64e16ef3dcab95afd497333d8fa12f');
export const SPAKE2_N = Point.fromHex('03d8bbd6c639c62937b04d997f38c3770719c629d7014d49a24b4f98baa1292b49');

export type Spake2Role = 'A' | 'B';

export interface Spake2Options {
  role: Spake2Role;
  /** Identity of role A. May be empty. */
  idA: Uint8Array;
  /** Identity of role B. May be empty. */
  idB: Uint8Array;
  /** The password-derived scalar, see `passwordScalar` / `secretScalar`. */
  w: bigint;
  /** Associated data folded into the confirmation keys. */
  aad?: Uint8Array;
  /** Ephemeral scalar. Only for test vectors: never pass one in production. */
  ephemeral?: bigint;
}

export interface Spake2Result {
  /** Shared secret. 16 bytes. Must not be used before `verifyPeer` succeeds. */
  Ke: Uint8Array;
  /** Our confirmation MAC to send to the peer. */
  confirmation: Uint8Array;
  /** The expected peer confirmation MAC. Kept for the caller's comparison. */
  verifyPeer(mac: Uint8Array): boolean;
  /** Full transcript TT, useful for binding signatures to this exchange. */
  transcript: Uint8Array;
}

function randomScalar(): bigint {
  // Rejection sampling over 32 bytes keeps the distribution uniform in [1, n).
  for (;;) {
    const k = bytesToBigInt(randomBytes(32));
    if (k > 0n && k < ORDER) return k;
  }
}

function decodePeerShare(bytes: Uint8Array) {
  if (bytes.length !== 65 || bytes[0] !== 0x04) throw new Error('SPAKE2: peer share must be an uncompressed P-256 point');
  const point = Point.fromBytes(bytes);          // throws if not on the curve
  point.assertValidity();
  if (point.is0()) throw new Error('SPAKE2: peer share is the identity');
  return point;
}

export class Spake2 {
  private readonly scalar: bigint;
  private readonly share: Uint8Array;
  private finished = false;

  constructor(private readonly opts: Spake2Options) {
    if (opts.w <= 0n || opts.w >= ORDER) throw new Error('SPAKE2: w is out of range');
    this.scalar = opts.ephemeral ?? randomScalar();
    if (this.scalar <= 0n || this.scalar >= ORDER) throw new Error('SPAKE2: ephemeral scalar out of range');
    const blind = opts.role === 'A' ? SPAKE2_M : SPAKE2_N;
    this.share = blind.multiply(opts.w).add(Point.BASE.multiply(this.scalar)).toBytes(false);
  }

  /** The message to send to the peer: pA for role A, pB for role B. */
  get outbound(): Uint8Array { return this.share; }

  /**
   * `aad` overrides the constructor's associated data, for protocols where it
   * includes values only known once the peer's message has arrived.
   */
  finish(peerShare: Uint8Array, aad?: Uint8Array): Spake2Result {
    // An ephemeral scalar must never be reused across two peer shares.
    if (this.finished) throw new Error('SPAKE2: this exchange has already been finished');
    this.finished = true;

    const { role, w, idA, idB } = this.opts;
    const peer = decodePeerShare(peerShare);
    const unblind = role === 'A' ? SPAKE2_N : SPAKE2_M;
    // P-256 has cofactor h = 1, so K = scalar · (peer − w·unblind).
    const K = peer.subtract(unblind.multiply(w)).multiply(this.scalar);
    if (K.is0()) throw new Error('SPAKE2: derived the identity element');

    const pA = role === 'A' ? this.share : peerShare;
    const pB = role === 'A' ? peerShare : this.share;
    const Kbytes = K.toBytes(false);
    const wBytes = bigIntToBytes(w, 32);
    const TT = concat(
      u64le(idA.length), idA,
      u64le(idB.length), idB,
      u64le(pA.length), pA,
      u64le(pB.length), pB,
      u64le(Kbytes.length), Kbytes,
      u64le(wBytes.length), wBytes,
    );
    const { Ke, KcA, KcB } = spake2KeySchedule(TT, aad ?? this.opts.aad);
    const macA = hmac(sha256, KcA, TT);
    const macB = hmac(sha256, KcB, TT);
    const mine = role === 'A' ? macA : macB;
    const theirs = role === 'A' ? macB : macA;
    return {
      Ke,
      confirmation: mine,
      verifyPeer: (mac: Uint8Array) => equalBytes(mac, theirs),
      transcript: TT,
    };
  }
}

/** Derived keys exposed for the RFC test vectors. */
export function spake2KeySchedule(TT: Uint8Array, aad: Uint8Array = new Uint8Array()) {
  const digest = sha256(TT);
  const Ka = digest.slice(16, 32);
  const keys = hkdf(sha256, Ka, undefined, concat(utf8('ConfirmationKeys'), aad), 32);
  return { Ke: digest.slice(0, 16), Ka, KcA: keys.slice(0, 16), KcB: keys.slice(16, 32) };
}

/** Reduces uniformly random bytes (at least 64 bits longer than n) to a non-zero scalar. */
export function bytesToScalar(bytes: Uint8Array): bigint {
  if (bytes.length < 40) throw new Error('SPAKE2: need at least 40 bytes to derive w');
  // RFC 9382 §3.2: reduce mod n with 64 extra bits so the bias is negligible.
  const w = bytesToBigInt(bytes) % ORDER;
  if (w === 0n) throw new Error('SPAKE2: derived a zero password scalar');
  return w;
}
